name: Publish on GitHub Pages

on:
  release:
    types: [published]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v2
      with:
        github_token: ${{ secrets.token}}
        publish_dir: .
        publish_branch: gh-pages
        destination_dir: ./${{ github.event.release.tag_name }}
        keep_files: true 

