name: Deploy

on:
 push:
  branches:
   - main
  tags:
   - 'v*' # Матч для тегов, начинающихся с "v"

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
   - name: Checkout code
    uses: actions/checkout@v2

   - name: Build and deploy
    uses: peaceiris/actions-gh-pages@v3
    with:
     # Исправленный секрет
     github_token: ${{ secrets.GITHUB_TOKEN }}
     publish_dir: ./
     publish_branch: gh-pages
     create_branch: true
     create_pull_request: true
     head: gh-pages 


