name: Deploy to GitHub Pages

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build project
        run: |
          npm install
          npm run build

      - name: Create version directory
        run: |
          VERSION=${{ github.event.release.tag_name }}
          mkdir -p "v$VERSION/en"
          mkdir -p "v$VERSION/ru"
          cp -r ./en/index.html "v$VERSION/en/index.html"
          cp -r ./ru/index.html "v$VERSION/ru/index.html"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
