name: Publish on GitHub Pages

on:
  release:
    types: [created]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 

    - name: Deploy to GitHub Pages
      uses: lolandvi/l4@v1
      with:
        github_token: ${{ secrets.token}}
        publish_dir: ./ 
        destination_dir: ./${{ github.event.release.tag_name }} 

