name: Deploy

on:
 push:
  branches:
   - main
  tags:
   - 'v*' # Матч для тегов, начинающихся с "v"

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
   - name: Checkout code
    uses: actions/checkout@v2

   - name: Build and deploy
    uses: peaceiris/actions-main@v3
    with:
     github_token: ${{ secrets.TOKEN }}
     publish_dir: ./
     publish_branch: main
     tag: ${{ github.ref_name }}
     create_branch: true
     create_pull_request: true
